
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = 'XL\xcf\xe9\xd7\xd26+SH\xb7#\xfb\xdcX\x9b'
    
_lr_action_items = {'LESS':([20,23,57,],[26,26,75,]),'LBRACKET':([55,],[73,]),'OPTIONS':([41,],[55,]),'RBRACE':([36,41,48,50,51,52,54,56,68,69,71,78,79,81,83,89,],[-2,-2,-10,-11,64,66,-2,-40,80,-44,-45,-12,-9,-43,-39,-46,]),'SEMI':([4,19,32,37,38,39,55,57,67,72,74,82,90,91,],[9,25,45,-25,-26,52,-2,-14,-24,83,-42,89,-41,-13,]),'COLON':([49,],[63,]),'COMMA':([33,34,35,36,37,38,39,48,50,51,57,62,67,73,78,79,84,85,86,91,94,],[-33,-34,46,-2,-25,-26,53,-10,-11,65,-14,-32,-24,-2,-12,-9,65,-16,92,-13,-15,]),'NATIVE':([3,5,7,8,9,10,12,14,15,16,17,22,25,40,45,64,66,80,],[-2,11,-5,-6,-3,-21,-20,-4,-18,-19,11,-17,-8,-27,-7,-22,-23,-29,]),'$end':([2,10,12,15,16,17,22,40,64,66,80,],[0,-21,-20,-18,-19,-1,-17,-27,-22,-23,-29,]),'INHERITS':([23,28,31,47,],[-2,-31,42,-30,]),'STRING':([63,77,],[78,88,]),'ENUM':([3,5,7,8,9,10,12,14,15,16,17,22,25,40,45,64,66,80,],[-2,13,-5,-6,-3,-21,-20,-4,-18,-19,13,-17,-8,-27,-7,-22,-23,-29,]),'MODULE':([0,],[1,]),'AS':([19,57,58,88,91,],[24,-14,76,93,-13,]),'IMPORT':([3,5,7,8,9,14,25,45,],[6,6,-5,-6,-3,-4,-8,-7,]),'IDENTIFIER':([1,6,11,13,18,24,26,29,36,41,42,46,53,54,56,65,68,69,70,71,73,75,76,81,83,89,92,93,],[4,19,20,21,23,32,34,38,49,-2,57,34,38,70,-40,49,70,-44,57,-45,49,57,87,-43,-39,-46,57,95,]),'MESSAGE':([3,5,7,8,9,10,12,14,15,16,17,22,25,40,45,64,66,80,],[-2,18,-5,-6,-3,-21,-20,-4,-18,-19,18,-17,-8,-27,-7,-22,-23,-29,]),'ON':([59,],[77,]),'LBRACE':([20,21,23,27,28,30,31,43,44,47,60,61,87,95,],[-2,29,-2,36,-31,41,-2,-2,-36,-30,-28,-38,-35,-37,]),'GREATER':([33,34,35,57,62,85,86,91,94,],[-33,-34,47,-14,-32,-16,91,-13,-15,]),'RBRACKET':([48,50,73,78,79,84,],[-10,-11,-2,-12,-9,90,]),'POLYMORPHIC':([23,28,31,43,44,47,87,],[-2,-31,-2,59,-36,-30,-35,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'message_body':([30,],[40,]),'message_header':([23,],[30,]),'imports':([3,],[5,]),'variables':([20,23,],[27,31,]),'module':([0,],[2,]),'message':([5,17,],[10,10,]),'native':([5,17,],[16,16,]),'field':([54,68,],[69,81,]),'import':([3,5,],[7,14,]),'type':([42,70,75,92,],[58,82,85,94,]),'variable_list':([26,],[35,]),'enum_value':([29,53,],[37,67,]),'enum':([5,17,],[12,12,]),'module_name':([0,],[3,]),'variable':([26,46,],[33,62,]),'message_options':([41,],[54,]),'types':([75,],[86,]),'enum_values':([29,],[39,]),'definition':([5,17,],[15,22,]),'data_field':([36,65,73,],[48,79,48,]),'message_tree':([43,],[60,]),'message_base':([31,],[43,]),'empty':([3,20,23,31,36,41,43,54,55,73,],[8,28,28,44,50,56,61,71,74,50,]),'fields':([54,],[68,]),'definitions':([5,],[17,]),'options':([55,],[72,]),'data_fields':([36,73,],[51,84,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> module","S'",1,None,None,None),
  ('module -> module_name imports definitions','module',3,'p_module','/Users/ivan/Workspace/pdef/python/src/pdef/parser.py',76),
  ('empty -> <empty>','empty',0,'p_empty','/Users/ivan/Workspace/pdef/python/src/pdef/parser.py',86),
  ('module_name -> MODULE IDENTIFIER SEMI','module_name',3,'p_module_name','/Users/ivan/Workspace/pdef/python/src/pdef/parser.py',93),
  ('imports -> imports import','imports',2,'p_imports','/Users/ivan/Workspace/pdef/python/src/pdef/parser.py',100),
  ('imports -> import','imports',1,'p_imports','/Users/ivan/Workspace/pdef/python/src/pdef/parser.py',101),
  ('imports -> empty','imports',1,'p_imports','/Users/ivan/Workspace/pdef/python/src/pdef/parser.py',102),
  ('import -> IMPORT IDENTIFIER AS IDENTIFIER SEMI','import',5,'p_import','/Users/ivan/Workspace/pdef/python/src/pdef/parser.py',109),
  ('import -> IMPORT IDENTIFIER SEMI','import',3,'p_import','/Users/ivan/Workspace/pdef/python/src/pdef/parser.py',110),
  ('data_fields -> data_fields COMMA data_field','data_fields',3,'p_data_fields','/Users/ivan/Workspace/pdef/python/src/pdef/parser.py',119),
  ('data_fields -> data_field','data_fields',1,'p_data_fields','/Users/ivan/Workspace/pdef/python/src/pdef/parser.py',120),
  ('data_fields -> empty','data_fields',1,'p_data_fields','/Users/ivan/Workspace/pdef/python/src/pdef/parser.py',121),
  ('data_field -> IDENTIFIER COLON STRING','data_field',3,'p_data_field','/Users/ivan/Workspace/pdef/python/src/pdef/parser.py',128),
  ('type -> IDENTIFIER LESS types GREATER','type',4,'p_type','/Users/ivan/Workspace/pdef/python/src/pdef/parser.py',135),
  ('type -> IDENTIFIER','type',1,'p_type','/Users/ivan/Workspace/pdef/python/src/pdef/parser.py',136),
  ('types -> types COMMA type','types',3,'p_types','/Users/ivan/Workspace/pdef/python/src/pdef/parser.py',145),
  ('types -> type','types',1,'p_types','/Users/ivan/Workspace/pdef/python/src/pdef/parser.py',146),
  ('definitions -> definitions definition','definitions',2,'p_definitions','/Users/ivan/Workspace/pdef/python/src/pdef/parser.py',153),
  ('definitions -> definition','definitions',1,'p_definitions','/Users/ivan/Workspace/pdef/python/src/pdef/parser.py',154),
  ('definition -> native','definition',1,'p_definition','/Users/ivan/Workspace/pdef/python/src/pdef/parser.py',161),
  ('definition -> enum','definition',1,'p_definition','/Users/ivan/Workspace/pdef/python/src/pdef/parser.py',162),
  ('definition -> message','definition',1,'p_definition','/Users/ivan/Workspace/pdef/python/src/pdef/parser.py',163),
  ('native -> NATIVE IDENTIFIER variables LBRACE data_fields RBRACE','native',6,'p_native','/Users/ivan/Workspace/pdef/python/src/pdef/parser.py',170),
  ('enum -> ENUM IDENTIFIER LBRACE enum_values SEMI RBRACE','enum',6,'p_enum','/Users/ivan/Workspace/pdef/python/src/pdef/parser.py',180),
  ('enum_values -> enum_values COMMA enum_value','enum_values',3,'p_enum_values','/Users/ivan/Workspace/pdef/python/src/pdef/parser.py',187),
  ('enum_values -> enum_value','enum_values',1,'p_enum_values','/Users/ivan/Workspace/pdef/python/src/pdef/parser.py',188),
  ('enum_value -> IDENTIFIER','enum_value',1,'p_enum_value','/Users/ivan/Workspace/pdef/python/src/pdef/parser.py',195),
  ('message -> MESSAGE IDENTIFIER message_header message_body','message',4,'p_message','/Users/ivan/Workspace/pdef/python/src/pdef/parser.py',202),
  ('message_header -> variables message_base message_tree','message_header',3,'p_message_header','/Users/ivan/Workspace/pdef/python/src/pdef/parser.py',216),
  ('message_body -> LBRACE message_options fields RBRACE','message_body',4,'p_message_body','/Users/ivan/Workspace/pdef/python/src/pdef/parser.py',224),
  ('variables -> LESS variable_list GREATER','variables',3,'p_variables','/Users/ivan/Workspace/pdef/python/src/pdef/parser.py',231),
  ('variables -> empty','variables',1,'p_variables','/Users/ivan/Workspace/pdef/python/src/pdef/parser.py',232),
  ('variable_list -> variable_list COMMA variable','variable_list',3,'p_variable_list','/Users/ivan/Workspace/pdef/python/src/pdef/parser.py',242),
  ('variable_list -> variable','variable_list',1,'p_variable_list','/Users/ivan/Workspace/pdef/python/src/pdef/parser.py',243),
  ('variable -> IDENTIFIER','variable',1,'p_variable','/Users/ivan/Workspace/pdef/python/src/pdef/parser.py',250),
  ('message_base -> INHERITS type AS IDENTIFIER','message_base',4,'p_message_base','/Users/ivan/Workspace/pdef/python/src/pdef/parser.py',257),
  ('message_base -> empty','message_base',1,'p_message_base','/Users/ivan/Workspace/pdef/python/src/pdef/parser.py',258),
  ('message_tree -> POLYMORPHIC ON STRING AS IDENTIFIER','message_tree',5,'p_message_tree','/Users/ivan/Workspace/pdef/python/src/pdef/parser.py',267),
  ('message_tree -> empty','message_tree',1,'p_message_tree','/Users/ivan/Workspace/pdef/python/src/pdef/parser.py',268),
  ('message_options -> OPTIONS options SEMI','message_options',3,'p_message_options','/Users/ivan/Workspace/pdef/python/src/pdef/parser.py',280),
  ('message_options -> empty','message_options',1,'p_message_options','/Users/ivan/Workspace/pdef/python/src/pdef/parser.py',281),
  ('options -> LBRACKET data_fields RBRACKET','options',3,'p_options','/Users/ivan/Workspace/pdef/python/src/pdef/parser.py',291),
  ('options -> empty','options',1,'p_options','/Users/ivan/Workspace/pdef/python/src/pdef/parser.py',292),
  ('fields -> fields field','fields',2,'p_fields','/Users/ivan/Workspace/pdef/python/src/pdef/parser.py',302),
  ('fields -> field','fields',1,'p_fields','/Users/ivan/Workspace/pdef/python/src/pdef/parser.py',303),
  ('fields -> empty','fields',1,'p_fields','/Users/ivan/Workspace/pdef/python/src/pdef/parser.py',304),
  ('field -> IDENTIFIER type SEMI','field',3,'p_field','/Users/ivan/Workspace/pdef/python/src/pdef/parser.py',311),
]
