#!/usr/bin/env python
#encoding: utf-8
import argparse
import logging
from pdef.common import PdefException
from pdef.compiler import Compiler


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Protocol definition compiler')
    parser.add_argument('--config', '-c', action='store', required=True,
                        help='json configuration file')
    parser.add_argument('--verbose', '-v', action='store_true')
    args = parser.parse_args()

    level = logging.DEBUG if args.verbose else logging.INFO
    logging.basicConfig(level=level, format='%(message)s')

    config = args.config
    compiler = Compiler()
    try:
        compiler.execute_config(config)
    except PdefException, e:
        logging.error("%s", e)
